[package]
name = "minio-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minio = "0.1.0"
tokio = "1.36.0"
