version: '3.8'
services:
  ota-backend:
    image: logicpi/ota-backend:0.5.1
    container_name: ota-backend
    ports:
      - 20000:20000
    environment:
      - FW_DB=postgres://craftor:3.1415926@ota-database:5432/firmware
    depends_on:
      - ota-database

  ota-server:
    image: logicpi/ota-server:0.4.2
    container_name: ota-server
    ports:
      - 9999:9999
    environment:
      - FW_SERVER=http://ota-backend:20000
      - FW_DB=postgres://craftor:3.1415926@ota-database:5432/firmware
    depends_on:
      - ota-backend
      - ota-database

  ota-database:
    image: logicpi/ota-database:0.5.2
    container_name: ota-database
    command: postgres -c 'max_connections=1000'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
