version: '3.8'
services:
  ota-file-server:
    image: logicpi/ota-file-server:0.1.3
    container_name: ota-file-server
    ports:
      - 20000:20000
    environment:
      - FW_DB=postgres://craftor:3.1415926@mcu-ota-pg:50000/firmware
    volumes:
      - /home/craftor/ftp:/app/ftp
    depends_on:
      - pg

  mcu-ota-server:
    image: logicpi/mcu-ota-server:0.1.9
    container_name: mcu-ota-server
    ports:
      - 9999:9999
    environment:
      - FW_SERVER=http://ota-file-server:20000
    depends_on:
      - ota-file-server
      - pg 

  pg:
    image: postgres:latest
    container_name: mcu-ota-pg
    ports:
      - 50000:5432
    environment:
      - POSTGRES_USER=craftor
      - POSTGRES_PASSWORD=3.1415926
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
