version: '3.8'
services:
  ota-backend:
    image: logicpi/ota-backend:0.3.0
    container_name: ota-backend
    ports:
      - 20000:20000
    environment:
      - FW_DB=postgres://craftor:3.1415926@pg:5432/firmware
    volumes:
      - /home/craftor/ftp/fw:/app/ftp
    depends_on:
      - pg

  ota-server:
    image: logicpi/ota-server:0.3.0
    container_name: ota-server
    ports:
      - 9999:9999
    environment:
      - FW_SERVER=http://ota-file-server:20000
      - FW_DB=postgres://craftor:3.1415926@pg:5432/firmware
    depends_on:
      - ota-backend
      - ota-database

  ota-database:
    image: logicpi/ota-database:0.3.0
    container_name: ota-database 
    command: postgres -c 'max_connections=1000'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
