version: '3.8'
services:
  ota-file-server:
    image: logicpi/ota-file-server:0.1.2
    container_name: ota-file-server
    ports:
      - 20000:20000
    volumes:
      - /home/craftor/ftp:/app/ftp

  mcu-ota-server:
    image: logicpi/mcu-ota-server:0.1.9
    container_name: mcu-ota-server
    ports:
      - 9999:9999
    environment:
      - FW_SERVER=http://ota-file-server:20000
    depends_on:
      - ota-file-server
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 50000:5432
    environment:
      - POSTGRES_USER=craftor
      - POSTGRES_PASSWORD=3.1415926
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
