version: '3.8'
services:
  ota-file-server:
    image: logicpi/ota-file-server:0.2.0
    container_name: ota-file-server
    ports:
      - 20000:20000
    environment:
      - FW_DB=postgres://craftor:3.1415926@pg:5432/firmware
    volumes:
      - /home/craftor/ftp/fw:/app/ftp
    depends_on:
      - pg

  mcu-ota-server:
    image: logicpi/mcu-ota-server:0.2.3
    container_name: mcu-ota-server
    ports:
      - 9999:9999
    environment:
      - FW_SERVER=http://ota-file-server:20000
      - FW_DB=postgres://craftor:3.1415926@pg:5432/firmware
    depends_on:
      - ota-file-server
      - pg

  pg:
    image: logicpi/firmware:0.2.2
    container_name: mcu-ota-pg
    command: postgres -c 'max_connections=1000'
    # environment:
    #   - POSTGRES_USER=craftor
    #   - POSTGRES_PASSWORD=3.1415926
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
