
CREATE USER docker;
CREATE DATABASE firmware;
GRANT ALL PRIVILEGES ON DATABASE firmware TO docker;

CREATE TABLE IF NOT EXISTS firmware_data (
    id SERIAL PRIMARY KEY,
    info TEXT NOT NULL,
    data BYTEA NOT NULL
);
